# Change these first
owner: shiermann # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: BMHME
    url: https://bmhme.at
    icon: https://www.bmhme.at/wp-content/uploads/2019/08/cropped-bmhme_favicon-192x192.png
  - name: Musikschule Donauland
    url: https://musikschule-donauland.at/
    icon: https://i1.wp.com/musikschule-donauland.at/wp-content/uploads/2019/06/cropped-MS-Logo-ohne-Schrift.jpg?fit=192%2C192&ssl=1
  - name: Musikverein Margarethen am Moos
    url: http://www.mv-margarethen.at/
  - name: Österreichischer Blasmusikverband
    url: https://www.blasmusik.at/
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: DuckDuckGo
    url: https://www.duckduckgo.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  links:
    - rel: stylesheet
      href: https://demo.upptime.js.org/global.css
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Hier wird die **response time** mit der BMHME Seite und anderen Webseiten von anderen Musikvereinen verglichen.
  navbar:
    - title: Status
      href: https://shiermann.github.io/upptime
    - title: GitHub
      href: https://github.com/shiermann/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
